{% set data = load_setup_py_data() %}

package:
  name: ipypdf
  version: {{ data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install -vv .
  noarch: python
  
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
      - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}
  

requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # build:
  #   - {{ compilers('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pywin32 # [win]
    - spacy
    - ipycanvas
    - ipycytoscape
    - ipyevents
    - ipywidgets
    - ipytree
    - numpy # 1.19.3
    - opencv
    - pandas
    - pdf2image
    - pip
    - pytesseract
    - tesseract
    - traitlets
    - spacy-model-en_core_web_lg
    # dependencies are defined in setup.py
    # {% for dep in data['install_requires'] %}
    # - {{ dep.lower() }}
    # {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest
  imports:
    - ipypdf

about:
  home: https://github.com/JoelStansbury/ipypdf
  summary: Jupyter widget for applying nlp to pdf documents
  license: {{ data.get('license') }}
  license_file: LICENSE
